# Generated by Django 4.0.6 on 2022-08-08 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=255, verbose_name='Nome da Cliente')),
                ('cnpj_cliente', models.CharField(max_length=14, unique=True, verbose_name='Cliente CNPJ')),
                ('telefone_cliente', models.CharField(max_length=14, verbose_name='Telefone da Cliente')),
                ('email_cliente', models.CharField(max_length=255, verbose_name='Email da Cliente')),
                ('endereco_cliente', models.CharField(max_length=255, verbose_name='Endereço do Cliente')),
                ('numero_endereco_cliente', models.CharField(max_length=8, verbose_name='Numero do Cliente')),
                ('cep_cliente', models.CharField(max_length=8, verbose_name='CEP da Cliente')),
                ('complemento_endereco_cliente', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento do Endereço')),
                ('cidade_cliente', models.CharField(max_length=255, verbose_name='Cidade da Cliente')),
                ('uf_cliente', models.CharField(max_length=2, verbose_name='UF da Cliente')),
            ],
            options={
                'verbose_name': 'Cadastro Cliente',
                'verbose_name_plural': 'Cadastro Cliente',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=255, verbose_name='Nome da Empresa')),
                ('cnpj_empresa', models.CharField(max_length=14, unique=True, verbose_name='Empresa CNPJ')),
                ('cep_empresa', models.CharField(max_length=8, verbose_name='CEP da Empresa')),
                ('endereco_empresa', models.CharField(max_length=255, verbose_name='Endereço da Empresa')),
                ('numero_endereco_empresa', models.CharField(max_length=8, verbose_name='Numero do Endereço')),
                ('complemento_endereco_empresa', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento do Endereço')),
                ('telefone_empresa', models.CharField(max_length=14, verbose_name='Telefone da Empresa')),
                ('email_empresa', models.CharField(max_length=255, verbose_name='Email da Empresa')),
                ('cidade_empresa', models.CharField(max_length=255, verbose_name='Cidade da Empresa')),
                ('uf_empresa', models.CharField(max_length=2, verbose_name='UF da Empresa')),
            ],
            options={
                'verbose_name': 'Cadastro Empresa',
                'verbose_name_plural': 'Cadastro Empresa',
            },
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(verbose_name='Disponível')),
            ],
            options={
                'verbose_name': 'Estoque',
                'verbose_name_plural': 'Estoque',
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fornecedor', models.CharField(max_length=255, verbose_name='Nome da Fornecedor')),
                ('cnpj_fornecedor', models.CharField(max_length=14, unique=True, verbose_name='Fornecedor CNPJ')),
                ('telefone_fornecedor', models.CharField(max_length=14, verbose_name='Telefone da Fornecedor')),
                ('email_fornecedor', models.CharField(max_length=255, verbose_name='Email da Fornecedor')),
                ('endereco_fornecedor', models.CharField(max_length=255, verbose_name='Endereço do Fornecedor')),
                ('numero_endereco_fornecedor', models.CharField(max_length=8, verbose_name='Numero do Fornecedor')),
                ('cep_fornecedor', models.CharField(max_length=8, verbose_name='CEP da Fornecedor')),
                ('complemento_endereco_fornecedor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento do Endereço')),
                ('cidade_fornecedor', models.CharField(max_length=255, verbose_name='Cidade da Fornecedor')),
                ('uf_fornecedor', models.CharField(max_length=2, verbose_name='UF da Fornecedor')),
            ],
            options={
                'verbose_name': 'Cadastro Fornecedor',
                'verbose_name_plural': 'Cadastro Fornecedor',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeProduto', models.CharField(max_length=255, verbose_name='Nome do Produto')),
                ('descricao_produto', models.CharField(max_length=255, verbose_name='Descrição do Produto')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrofacil.cliente', verbose_name='Clientes')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrofacil.produto', verbose_name='Produtos')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
            },
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrofacil.fornecedor', verbose_name='Fornecedores')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrofacil.produto', verbose_name='Produtos')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
            },
        ),
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(verbose_name='Pago ?')),
                ('compras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrofacil.produto', verbose_name='Produtos')),
                ('vendas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrofacil.cliente', verbose_name='Clientes')),
            ],
            options={
                'verbose_name': 'Caixa',
                'verbose_name_plural': 'Caixa',
            },
        ),
    ]
