# Generated by Django 4.0.6 on 2022-08-08 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agrofacil', '0002_remove_estoque_status_produto_estoque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compras',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='estoque',
        ),
        migrations.AddField(
            model_name='estoque',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agrofacil.produto', verbose_name='Produtos'),
            preserve_default=False,
        ),
    ]
