# Generated by Django 4.0.6 on 2022-08-08 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agrofacil', '0004_estoque_quantidade_estoque_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrofacil.produto', unique=True, verbose_name='Produtos'),
        ),
    ]
