# Generated by Django 4.0.6 on 2022-08-09 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agrofacil', '0005_alter_estoque_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrofacil.produto', verbose_name='Produtos'),
        ),
    ]
