# Generated by Django 4.0.6 on 2022-08-09 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agrofacil', '0006_alter_estoque_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agrofacil.estoque', verbose_name='Produtos'),
            preserve_default=False,
        ),
    ]
