# Generated by Django 4.0.6 on 2022-08-09 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agrofacil', '0009_compras_estoque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compras',
            name='Estoque',
        ),
    ]
