# Generated by Django 4.0.6 on 2022-08-09 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agrofacil', '0010_remove_compras_estoque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compras',
            name='produto',
        ),
    ]
