# Generated by Django 4.0.6 on 2022-08-09 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agrofacil', '0011_remove_compras_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agrofacil.compras', verbose_name='Vendas'),
        ),
        migrations.AddField(
            model_name='estoque',
            name='venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agrofacil.vendas', verbose_name='Vendas'),
        ),
    ]
