# Generated by Django 4.0.6 on 2022-08-09 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agrofacil', '0012_estoque_compra_estoque_venda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoque',
            name='compra',
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='venda',
        ),
        migrations.AlterField(
            model_name='vendas',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrofacil.estoque', verbose_name='Produtos'),
        ),
    ]
