# Generated by Django 4.0.6 on 2022-08-09 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agrofacil', '0013_remove_estoque_compra_remove_estoque_venda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrofacil.produto', verbose_name='Produtos'),
        ),
    ]
