# Generated by Django 4.0.6 on 2022-08-09 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agrofacil', '0014_alter_vendas_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrofacil.estoque', verbose_name='Produtos'),
        ),
    ]
