# Generated by Django 4.0.6 on 2022-08-09 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agrofacil', '0016_alter_vendas_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendas',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='vendas',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='vendas',
            name='valor',
        ),
        migrations.AddField(
            model_name='vendas',
            name='estoque',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agrofacil.estoque', verbose_name='Estoque'),
            preserve_default=False,
        ),
    ]
