# Generated by Django 4.0.6 on 2022-08-09 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agrofacil', '0018_compras_estoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='compras',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agrofacil.fornecedor', verbose_name='Compra'),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='vendas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agrofacil.cliente', verbose_name='Venda'),
        ),
    ]
