# Generated by Django 4.0.6 on 2022-07-07 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=255)),
                ('telefone_cliente', models.CharField(max_length=15)),
                ('cpf_cliente', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='BancoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_banco_cliente', models.CharField(max_length=11)),
                ('tipo_conta_cliente', models.CharField(max_length=11)),
                ('numero_conta_cliente', models.CharField(max_length=11)),
                ('banco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='emprestimos.cliente', verbose_name='banco_cliente')),
            ],
        ),
    ]
