# Generated by Django 4.0.6 on 2022-07-07 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bancocliente',
            name='banco',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='emprestimos.cliente'),
            preserve_default=False,
        ),
    ]
