# Generated by Django 4.0.6 on 2022-07-07 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0003_alter_bancocliente_banco'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bancocliente',
            old_name='banco',
            new_name='cliente_banco',
        ),
        migrations.RenameField(
            model_name='bancocliente',
            old_name='nome_banco_cliente',
            new_name='nome_banco',
        ),
        migrations.RenameField(
            model_name='bancocliente',
            old_name='numero_conta_cliente',
            new_name='numero_conta',
        ),
        migrations.RenameField(
            model_name='bancocliente',
            old_name='tipo_conta_cliente',
            new_name='tipo_conta',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nome_cliente',
            new_name='cliente',
        ),
    ]
